/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.Diem_Thi;
import Model.ThiSinh;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddDiem extends javax.swing.JDialog {

    /**
     * Creates new form AddDiem
     */
    private HomeFrm1 home;
    public AddDiem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home = (HomeFrm1) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KhoiThiDTText = new javax.swing.JTextField();
        SbdDTText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HoTenDTText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AddDtBtn = new javax.swing.JButton();
        CancelDtBtn = new javax.swing.JButton();
        ToanText = new javax.swing.JTextField();
        VanText = new javax.swing.JTextField();
        AnhText = new javax.swing.JTextField();
        VatLiText = new javax.swing.JTextField();
        SinhText = new javax.swing.JTextField();
        HoaText = new javax.swing.JTextField();
        SuText = new javax.swing.JTextField();
        DiaLiText = new javax.swing.JTextField();
        GdcdText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TohopText = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Thêm Thông Tin Điểm Thi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Thông Tin Thí Sinh");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Số Báo Danh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ và Tên");
        jLabel3.setMaximumSize(new java.awt.Dimension(87, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(87, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(87, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Khối Thi");
        jLabel4.setMaximumSize(new java.awt.Dimension(87, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(87, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(87, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Toán");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ngữ Văn");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("T.Anh");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Thông Tin Điểm Thi");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Hóa Học");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Vật Lý");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Địa Lí");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Lịch Sử");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Sinh Học");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("GDCD");

        AddDtBtn.setBackground(new java.awt.Color(204, 204, 255));
        AddDtBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddDtBtn.setText("Add");
        AddDtBtn.setToolTipText("");
        AddDtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDtBtnActionPerformed(evt);
            }
        });

        CancelDtBtn.setBackground(new java.awt.Color(204, 204, 255));
        CancelDtBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelDtBtn.setText("Cancel");
        CancelDtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelDtBtnActionPerformed(evt);
            }
        });

        ToanText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        VanText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AnhText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        VatLiText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SinhText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        HoaText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SuText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        DiaLiText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        GdcdText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Tổ Hợp");

        TohopText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setText("About me");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(KhoiThiDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoaText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SinhText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SuText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaLiText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GdcdText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TohopText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddDtBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ToanText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VanText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AnhText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VatLiText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(HoTenDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(CancelDtBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SbdDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SbdDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTenDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoiThiDTText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VatLiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SinhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaLiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GdcdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TohopText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDtBtn)
                    .addComponent(CancelDtBtn))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AddDtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDtBtnActionPerformed
        String sbd = "";
        String name = "", khoi_thi = "";
        float toan = 0, van = 0, anh = 0, vli = 0, hoa = 0, sinh = 0, su = 0, dli = 0, gdcd = 0, tohop = 0;
        boolean isOK = true;

        sbd = SbdDTText.getText();
        if (Kiemtra(sbd)) {
            JOptionPane.showMessageDialog(null, "Số báo danh đã được nhập trước đó, vui lòng nhập số khác");
            isOK = false;
        }
        
        try {
            // Kiểm tra xem chuỗi nhập vào có
            if (!sbd.matches("[a-zA-Z0-9]+")) {
                throw new Exception("Chuỗi nhập vào không hợp lệ");
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hãy nhập đúng định dạng,"
                    + " chỉ có thể nhập các chữ cái và chữ số");
            isOK = false;
        }
        
        
        try {
            // Kiểm tra xem chuỗi nhập vào có
            if (!sbd.matches("[a-zA-Z0-9]+")) {
                throw new Exception("Chuỗi nhập vào không hợp lệ");
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hãy nhập đúng định dạng,"
                    + " chỉ có thể nhập các chữ cái và chữ số");
            isOK = false;
        }

        name = HoTenDTText.getText();
        try {
            // Kiểm tra xem chuỗi nhập vào có chứa ký tự đặc biệt hoặc số không
            if (!name.matches("^[a-zA-Z\\s]+$")) {
                throw new Exception("Chuỗi nhập vào không hợp lệ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hãy nhập "
                + "đúng định dạng, chỉ có thể nhập các chữ cái không có số và kí tự đặc biệt.");
            isOK = false;
        }

        khoi_thi = KhoiThiDTText.getText();
        try {
            // Kiểm tra chuỗi nhập vào có đúng định dạng không
            if (!khoi_thi.matches("^(A1?|B1?|C1?|D7?|[ABCDEF])$")) {
                throw new Exception("Chuỗi nhập vào không hợp lệ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Khối thi không hợp lệ. "
            + "Vui lòng chỉ nhập khối thi là A, A1, B, B1, C, C1, D hoặc D7.");
            isOK = false;
        }

        //Khối D
        
        if (khoi_thi.equals("D")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
        
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
        
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            tohop = toan + van + anh;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);
            
            HoaText.setEditable(false);
            VatLiText.setEditable(false);
            SinhText.setEditable(false);
            SuText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        //Khối D7
        
        if (khoi_thi.equals("D7")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
        
            try {
                hoa = Float.parseFloat(HoaText.getText());
                if (hoa < 0 || hoa > 10) {
                    throw new Exception("Điểm Hóa không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Hóa không hợp lệ");
                isOK = false;
            }
        
           
            tohop = toan + hoa + anh;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);
            
            VatLiText.setEditable(false);
            SinhText.setEditable(false);
            SuText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        //Khối A
        
        if (khoi_thi.equals("A")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            try {
                vli = Float.parseFloat(VatLiText.getText());
                if (vli < 0 || vli > 10) {
                    throw new Exception("Điểm Vật Lý không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Vật lí không hợp lệ");
                isOK = false;
            }
            
            try {
                hoa = Float.parseFloat(HoaText.getText());
                if (hoa < 0 || hoa > 10) {
                    throw new Exception("Điểm Hóa Học không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Hóa không hợp lệ");
                isOK = false;
            }
            
            tohop = toan + vli + hoa; 
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);
            
            SinhText.setEditable(false);
            SuText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        // Khối A1
        if (khoi_thi.equals("A1")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            try {
                vli = Float.parseFloat(VatLiText.getText());
                if (vli < 0 || vli > 10) {
                    throw new Exception("Điểm Vật Lý không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Vật lí không hợp lệ");
                isOK = false;
            }
            
            tohop = vli + anh + toan;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);

            
            HoaText.setEditable(false);
            SinhText.setEditable(false);
            SuText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        //Khối B
        if (khoi_thi.equals("B")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            try {
                hoa = Float.parseFloat(HoaText.getText());
                if (hoa < 0 || hoa > 10) {
                    throw new Exception("Điểm Hóa Học không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Hóa không hợp lệ");
                isOK = false;
            }
            
            try {
                sinh = Float.parseFloat(SinhText.getText());
                if (sinh < 0 || sinh > 10) {
                    throw new Exception("Điểm Sinh Học không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            tohop = toan + hoa + sinh;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);

            VatLiText.setEditable(false);
            SuText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        //Khối B1
        if (khoi_thi.equals("B1")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            try {
                sinh = Float.parseFloat(SinhText.getText());
                if (sinh < 0 || sinh > 10) {
                    throw new Exception("Điểm Sinh Học không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                su = Float.parseFloat(SuText.getText());
                if (su < 0 || su > 10) {
                    throw new Exception("Điểm Lịch Sử không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Lịch Sử không hợp lệ");
                isOK = false;
            }
            
            tohop = toan + sinh + su;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);

            VatLiText.setEditable(false);
            HoaText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        //Khối C
        if (khoi_thi.equals("C")) {
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            try {
                su = Float.parseFloat(SuText.getText());
                if (su < 0 || su > 10) {
                    throw new Exception("Điểm Lịch Sử không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Lịch Sử không hợp lệ");
                isOK = false;
            }
            
            try {
                dli = Float.parseFloat(DiaLiText.getText());
                if (dli < 0 || dli > 10) {
                    throw new Exception("Điểm Địa Lí không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Địa Lí không hợp lệ");
                isOK = false;
            }
            
            tohop = van + su + dli;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);

            VatLiText.setEditable(false);
            HoaText.setEditable(false);
            SinhText.setEditable(false);
            GdcdText.setEditable(false);
        }
        
        //Khối C1
        if (khoi_thi.equals("C1")) {             
            try {
                toan = Float.parseFloat(ToanText.getText());
                if (toan < 0 || toan > 10) {
                    throw new Exception("Điểm Toán không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Toán không hợp lệ");
                isOK = false;
            }
            
            try {
                van = Float.parseFloat(VanText.getText());
                if (van < 0 || van > 10) {
                    throw new Exception("Điểm Văn không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Văn không hợp lệ");
                isOK = false;
            }
            
            try {
                anh = Float.parseFloat(AnhText.getText());
                if (anh < 0 || anh > 10) {
                    throw new Exception("Điểm Anh không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Anh không hợp lệ");
                isOK = false;
            }
            
            try {
                su = Float.parseFloat(SuText.getText());
                if (su < 0 || su > 10) {
                    throw new Exception("Điểm Lịch Sử không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Lịch Sử không hợp lệ");
                isOK = false;
            }
            
            try {
                gdcd = Float.parseFloat(GdcdText.getText());
                if (gdcd < 0 || gdcd > 10) {
                    throw new Exception("Điểm Giáo dục công dân không hợp lệ. Vui lòng nhập điểm từ 0 đến 10.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Điểm Giáo dục công dân không hợp lệ");
                isOK = false;
            }
            
            tohop = van + su + gdcd;
            TohopText.setText(String.valueOf(tohop));
            TohopText.setEditable(false);

            HoaText.setEditable(false);
            VatLiText.setEditable(false);
            DiaLiText.setEditable(false);
            GdcdText.setEditable(false);
        }
       
        tohop = Float.parseFloat(TohopText.getText());

        if(isOK) {
            Diem_Thi diemthi = new Diem_Thi(sbd, name, khoi_thi, toan, van, anh, vli, hoa, sinh, su, dli, gdcd, tohop);
            home.addDiemThi(diemthi);
            JOptionPane.showMessageDialog(rootPane, "Thêm Thành Công");
            Clear_Sau_Khi_Nhap();
            this.dispose();

        }
    }//GEN-LAST:event_AddDtBtnActionPerformed

    
     public boolean Kiemtra(String Sbd) {
        for (ThiSinh ts : home.getDiem_This()) {
            if (Sbd.equals(ts.getSbd()))
                return true;
            }
        return false;
    }
     
    public void Clear_Sau_Khi_Nhap() {
        SbdDTText.setText("");
        HoTenDTText.setText("");
        KhoiThiDTText.setText("");
    }
    
    private void CancelDtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelDtBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelDtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDiem dialog = new AddDiem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDtBtn;
    private javax.swing.JTextField AnhText;
    private javax.swing.JButton CancelDtBtn;
    private javax.swing.JTextField DiaLiText;
    private javax.swing.JTextField GdcdText;
    private javax.swing.JTextField HoTenDTText;
    private javax.swing.JTextField HoaText;
    private javax.swing.JTextField KhoiThiDTText;
    private javax.swing.JTextField SbdDTText;
    private javax.swing.JTextField SinhText;
    private javax.swing.JTextField SuText;
    private javax.swing.JTextField ToanText;
    private javax.swing.JTextField TohopText;
    private javax.swing.JTextField VanText;
    private javax.swing.JTextField VatLiText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
